### PR TITLE
Resources improved

### PR DESCRIPTION
**Pull request by Narfss**
## What and Why?
Current resources show warning on gradle build.

Example:

```
AAPT warning(Job{title=Cruncher fab_bg_mini.png, latch=BooleanLatch{signaled=false}, result=false}): ...build/intermediates/exploded-aar/com.getbase/floatingactionbutton/1.9.0/res/drawable-xhdpi-v4/fab_bg_mini.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT warning(Job{title=Cruncher fab_bg_normal.png, latch=BooleanLatch{signaled=false}, result=false}): ...build/intermediates/exploded-aar/com.getbase/floatingactionbutton/1.9.0/res/drawable-hdpi-v4/fab_bg_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT warning(Job{title=Cruncher fab_bg_mini.png, latch=BooleanLatch{signaled=false}, result=false}): ...build/intermediates/exploded-aar/com.getbase/floatingactionbutton/1.9.0/res/drawable-hdpi-v4/fab_bg_mini.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT warning(Job{title=Cruncher fab_bg_normal.png, latch=BooleanLatch{signaled=false}, result=false}): ...build/intermediates/exploded-aar/com.getbase/floatingactionbutton/1.9.0/res/drawable-mdpi-v4/fab_bg_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT warning(Job{title=Cruncher fab_bg_mini.png, latch=BooleanLatch{signaled=false}, result=false}): ...build/intermediates/exploded-aar/com.getbase/floatingactionbutton/1.9.0/res/drawable-mdpi-v4/fab_bg_mini.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited
AAPT warning(Job{title=Cruncher fab_bg_normal.png, latch=BooleanLatch{signaled=false}, result=false}): ...build/intermediates/exploded-aar/com.getbase/floatingactionbutton/1.9.0/res/drawable-xhdpi-v4/fab_bg_normal.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited

```

The new proposed resources are more light and don't show errors.

### CODE REVIEW

**Comment by maksim88** [comment]
+1 for this, just wanted to make the same pull-request

**Comment by chalup** [comment]
Nice. Care to share the magic incantations you used to process the resources?

**Comment by maksim88** [comment]
You can use something like this to do so (coming from jake wharton):
find . -path 'src/main/res/' -name '*.png' -exec exiftool -overwrite_original -all= {} \;

**Comment by Narfss** [comment]
@chalup Thanks for the merge. In this case a used the ImageOptim app (https://imageoptim.com/)
@maksim88 thanks for the command.

:+1:

**Pull request merged**
