### PR TITLE
Fab menu icon

### PR DESCRIPTION
**Pull request by k0shk0sh**
Added support to set FloatingActionsMenu icon and whether to enable rotating the icon or no.

### CODE REVIEW

**Comment by JonathanMerritt** [comment]
@k0shk0sh

Wondering how to achieve this. Would I need to include the library locally and ads your changes?

Be awesome if it was included in lib.

**Comment by k0shk0sh** [comment]
@JonathanMerritt  you could pull this request form my profile, the owner of this repo never merge the commit. so i can't do anything about it :). just after you pull it from my profile replace it with your current one.

**Comment by chalup** [comment]
@k0shk0sh Protip: if you want your commits to be merged, do not change formatting, do not add bunch of useless comments, do not leave commented out code, and rebase/merge your code on regular basis. It also doesn't hurt to ask what are the plans regarding some feature **before** writing any code.

On top of that I do not consider your solution final: one problem is that you didn't change overshoot interpolator or rotation angle, which make sense specifically with plus icon. Other thing is, if you use Inbox app as a reference, you cannot use different icon for expanded and collapsed FAM.

@JonathanMerritt if you consider @k0shk0sh's solution good enough for you, clone his repo change the version in gradle.properties, put it into local maven repo with `gradle clean installArch` and use this version.

**Comment by JonathanMerritt** [comment]
My project no longer requires this. But thanks for the info.

**Pull request closed without merging**
