### PR TITLE
Menu inflate

### PR DESCRIPTION
**Pull request by alorma**
Add ability to inflae menu from menu reurce instead of create directly on XML

PD: labels still not work, can you tify why not?

PDD: Only commit 41ca908 needs to merged

[Review on Reviewable](https://reviewable.io/reviews/futuresimple/android-floating-action-button/94)

### CODE REVIEW

**Comment by alorma** [comment]
Fixed labels not apear, was alignement problem!

**Comment by chalup** [comment]
I like the idea, but it would definitely need more work:

1. The FAB colors should match the main FAM button color.
1. Submenus should be handled somehow (runtime error? FAM inside FAM, a.k.a. FAMception?)
1. Decide how to handle gazillion of other menu attributes (http://developer.android.com/guide/topics/resources/menu-resource.html)
1. Can you call `inflate` multiple times to add buttons from mutliple xml menus? What should be the order of the added items? (probably it should behave like all the other Android menus).
1. It would be nice to set the items directly in xml, i.e. have the `fab_items` attribute which points to menu resource.

And from implementation point of view, using reflection to instantiate internal Android class is probably not the best idea.

**Comment by alorma** [comment]
I know it's not the best idea, but get Menu it's complicated, because it's
a private classe of the sistem... it needs more work, i know.

Will work on it an see how can it be improved

**Comment by alorma** [comment]
- Menu inflated without reflection.
- Color match parent

**Comment by alorma** [comment]
Done.

- Order in category
- Colors
- Set size to mini (maybe need setter)
- Clear items

**Comment by alorma** [comment]
I think now it can be merged, maybein an experimental branch, and work since this, improve and make small changes... for now is usable

**Pull request closed without merging**
